global:
  scrape_interval: 30s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
  - job_name: grafana
    static_configs:
      - targets:
        - grafana:3000
  - job_name: traefik
    static_configs:
      - targets:
        - traefik:8080
  - job_name: nginx
    static_configs:
      - targets:
        - nginx-exporter:9113
  - job_name: node
    static_configs:
      - targets: 
        - node-exporter:9100
  - job_name: golang
    static_configs:
      - targets:
        - api:8080
        labels:
          app: 'ViewShare'
  - job_name: etcd
    static_configs:
    - targets: 
      - etcd1:2379
      - etcd2:2379
      - etcd3:2379

      
  - job_name: patroni
    static_configs:
      - targets:
        - db-pg-node-01:8008
        - db-pg-node-02:8008
        - db-pg-node-03:8008
  - job_name: postgres
    static_configs:
      - targets:
        # - db:5432
        # - db-master:5432
        # - db-slave-01:5432
        # - db-slave-02:5432
        - db-pg-node-01:5432
        - db-pg-node-02:5432
        - db-pg-node-03:5432
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187