global:
  scrape_interval: 30s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: grafana
    static_configs:
      - targets:
        - grafana:3000
  - job_name: traefik
    static_configs:
      - targets:
        - traefik:8080
  - job_name: nginx
    static_configs:
      - targets:
        - nginx-exporter:9113
  - job_name: golang
    static_configs:
      - targets:
        - api:8080
        labels:
          app: 'ViewShare'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'postgres'
    static_configs:
      - targets:
        - db:5432
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187